name: build
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: build production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3
        with:
          cmd: up
      - uses: borales/actions-yarn@v3
        with:
          cmd: build
      - uses: papeloto/action-zip@v1
        with:
          files: build/
          dest: build.zip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.workspace }}/build.zip
          token: ${{ secrets.GITHUB_TOKEN }}
